dockerregistry:
  image: registry:2
  hostname: dockerregistry
  ports:
    - "5000:5000"

zookeeper:
  image: mesoscope/zookeeper
  hostname: zookeeper
  environment:
    - SERVER_ID=mesoscope-zk
  ports:
    - "2181:2181"

mesosmaster:
  image: mesoscope/mesos-master
  hostname: mesosmaster
  links:
    - zookeeper
  environment:
    - MESOS_ZK=zk://zookeeper:2181/mesos
    - MESOS_PORT=5050
    - MESOS_LOG_DIR=/var/log/mesos
    - MESOS_QUORUM=1
    - MESOS_REGISTRY=in_memory
    - MESOS_WORK_DIR=/var/lib/mesos
  ports:
    - "5050:5050"

mesosmarathon:
  image: mesoscope/mesos-marathon
  hostname: mesosmarathon
  links:
    - zookeeper
  command: --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon
  ports:
    - "8080:8080"

mesosaurora:
  image: mesoscope/mesos-aurora
  hostname: mesosaurora
  links:
    - zookeeper
    - mesosmaster
  ports:
    - "8081:8081"
    - "8083:8083"

mesosslave:
  image: mesoscope/mesos-slave
  hostname: mesosslave
  links:
    - zookeeper
    - dockerregistry
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_LOG_DIR=/var/log/mesos
    - MESOS_LOGGING_LEVEL=INFO
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_WORK_DIR=/var/mesos
  ports:
    - "5051:5051"
    - "31000-31009:31000-31009"
